---
title: "Minimal EDI package generated using EMLassemblyline and ediutilities"
author: "Joe Futrelle"
date: "2022-01-24"
output: html_notebook
---

Libraries used

```{r}
# two of the required packages are installed from GitHub
# library(remotes)
# remotes::install_github("EDIorg/EMLassemblyline")
# remotes::install_github("WHOIGit/ediutilities")

library(EMLassemblyline)
library(ediutilities)
library(here)
library(lubridate)
library(stringr)
library(dplyr)
```

Read example data table

```{r}
data_table <- read.csv(here('nes_lter_events_raw.csv'))
data_table$dateTime8601 <-ymd_hms(data_table$dateTime8601)
data_table$Cast <- str_replace(data_table$Cast,'\\.0','')
data_table <- data_table %>% select(-c(Unnamed..8, Unnamed..9, Unnamed..10, Unnamed..11, Unnamed..12, Unnamed..13))

data_table$Station <- str_replace(data_table$Station, 'Cast*\\n[0-9]+    ', '')
data_table$Station <- str_replace(data_table$Station, '\\n.*', '')
data_table$Station <- str_replace(data_table$Station, '\\nName:.*', '')

data_table$Comment <- str_replace_all(data_table$Comment, ',', ';')

write.table(data_table, 'nes_lter_events.csv', row.names = FALSE, sep = ",", qmethod = c("escape", "double"))
```

Read the Excel metadata template and generate text templates used by
EMLassemblyline

```{r}
excel_to_template(here('nes-lter-minimal-info'), 'nes_lter_events', rights='CC0')
```
Generate the package and insert the parent project node into the resulting EML

```{r}
pkg_id <- 'knb-lter-nes.20.1'

make_eml(here(),
         dataset.title='Demonstration of minimal EDI package',
         data.table='nes_lter_events.csv',
         data.table.description='Example NES-LTER data',
         data.table.name = 'Subset of NES-LTER nutrient data',
         temporal.coverage = temporal_coverage(data_table$dateTime8601),
         geographic.description = "NES-LTER Transect",
         geographic.coordinates = geographic_coordinates(data_table$Latitude, data_table$Longitude),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

project_insert(pkg_id)
```
